#!/usr/local/bin/python3 blueclawai

import argparse
import sys
import requests
import shlex


URL = 'http://127.0.0.1:8000'
version = "1.1.0"


def parser_init(running=False):
    parser = argparse.ArgumentParser(description="A command to run the BlueClaw locally on your terminal")
    subparsers = parser.add_subparsers(dest='command', help='Available commands')

    if running:
        start_parser = subparsers.add_parser('/start_server', help='Start to run the server and model locally')
        # start_parser.add_argument('-m','--model', type=str, default='llm', help='Choosing the model to start running')
        start_parser.set_defaults(func=start)
    else:
        request_parser = subparsers.add_parser('request', help='Request to run the llm model')
        request_parser.add_argument('-q','--query', type=str, help='text or query to ask the model')
        # request_parser.add_argument('-m', '--model', type=str, default='llm', help='Choosing the Artificial Intelligence model')
        request_parser.add_argument('-t', '--tool', type=bool, default=False, help='Enable/Disable to allow the tool executives locally')
        request_parser.set_defaults(func=request)

        start_parser = subparsers.add_parser('start_server', help='Start to run the server and model locally')
        # start_parser.add_argument('-m','--model', type=str, default='llm', help='Choosing the model to start running')
        start_parser.set_defaults(func=start)

        stop_parser = subparsers.add_parser('stop_server', help='stop the server and model locally')
        # stop_parser.add_argument('-m','--model', type=str, default='llm', help='Choosing the model to stop running')
        stop_parser.set_defaults(func=stop)
        
        run_parser = subparsers.add_parser('run', help='Run the model')
        run_parser.add_argument('-m', '--model', type=str, default='llm', help='Choosing the Artificial Intelligence model')
        # stop_parser.add_argument('-m','--model', type=str, default='llm', help='Choosing the model to stop running')
        run_parser.set_defaults(func=run)
    
    return parser


def request(args):
    params = {
        "query": args.query
    }
    response = requests.get(f'{URL}/request/', params=params)

    if response.status_code == 200:
        data = response.json()
        print(data["ai_response"])
    else:
        print(f"Error: Received status code {response.status_code}")


def start(args):
    pass


def stop(args):
    pass


def list_model(args):
    pass


def run(args):
    parser = parser_init(running=True)

    while True:
        user = input()

        args_list = shlex.split(user)
        try:
            args = parser.parse_args(args_list)

            if args.command:
                args.func(args)
            else:
                # If no command is provided, show help
                parser.print_help()
        except Exception as e:
            print("Error")
            continue


def main():
    parser = parser_init()

    args = parser.parse_args()

    if args.command:
        args.func(args)
    else:
        # If no command is provided, show help
        parser.print_help()

if __name__ == "__main__":
    main()

