#!/usr/local/bin/python3 .blueclawai/blueclawai 
from server.parser import parser_init

__VERSION__ = "1.2.0"


if __name__ == "__main__":
    parser = parser_init()

    args = parser.parse_args()

    if args.command:
        args.func(args)
    else:
        # If no command is provided, show help
        parser.print_help()

